name: webapi-pr-validator
author: TeamWebAPI <dl-WebAPI@dr.dk>
description: Validate title of PRs to follow the conventional specification. (https://www.conventionalcommits.org/).
runs:
  using: docker
  image: Dockerfile